# Generated by Django 4.0.6 on 2023-02-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('info', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, default='/model3d.png', null=True, upload_to='')),
            ],
        ),
    ]
